api/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name='api'
urlpatterns = [
   path('',views.overview, name="overview"),
   path('verify/',views.verify, name="verify",)
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
    path('api/',include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='store'
urlpatterns = [
    path('',views.store, name='store' ),
    path('cart/',views.cart, name='cart'),
    path('checkout/',views.checkout, name='checkout'),
    path('update_item/',views.updateItem, name='updateItem'),
    path('process_order/',views.processOrder, name='processOrder'),
    path('payment_form/<str:pk>/',views.payment, name='payment'),
    path('login/',views.login, name='login'),
    path('register/',views.register, name='register'),
    path('logout/',views.logout, name='logout'),
    path('product/<str:pk>', views.product, name='product'),
    path('delete/<str:pk>/<str:pk2>', views.delete, name='delete'),
    path('rate/<str:pk>',views.rate, name='rate'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Customer(models.Model):
    user=models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name=models.CharField(null=True, max_length=200)
    email=models.CharField(max_length=200)
    phone=models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name



class Product(models.Model):
    name=models.CharField(max_length=200)
    price=models.FloatField()
    digital=models.BooleanField(default=False, null=True, blank=True)
    image=models.ImageField(null=True, blank=True)
    description=models.TextField(null=True, blank=True)
    def __str__(self):
        return self.name
    
    @property
    def imageURL(self):
        try:
            url=self.image.url
        except:
            url=''
        return url




class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered=models.DateTimeField(auto_now_add=True)
    complete=models.BooleanField(default=False)
    transaction_id=models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping=False
        orderitems=self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital==False:
                shipping=True
        return shipping

    @property
    def get_cart_total(self):
        orderitems=self.orderitem_set.all()
        total=sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems=self.orderitem_set.all()
        total=sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product=models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order=models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity=models.IntegerField(default=0, null=True, blank=True)
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    @property
    def get_total(self):
        total=self.quantity*self.product.price
        return total


class ShippingAddress(models.Model):
    customer=models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    order=models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    address=models.CharField(max_length=400, null=False)
    city=models.CharField(max_length=100, null=False)
    state=models.CharField(max_length=100, null=False)
    zipcode=models.CharField(max_length=50, null=False)
    date_added=models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.address


class Comment(models.Model):
    customer=models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    product=models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    text=models.TextField(null=True, blank=True)
    posted_at=models.DateTimeField(null=True, auto_now_add=True)



class Rating(models.Model):
    customer=models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
    product=models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    rated=models.IntegerField(default=0)

store/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import *
import json
import datetime
from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.auth import authenticate, login as auth_login, logout as d_logout
from django.contrib.auth.models import User, UserManager
from django.contrib.auth.decorators import login_required
import re
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
@login_required(login_url='store:login')
def store(request):
    if request.user.is_authenticated:
        customer=request.user.customer
        order, createed=Order.objects.get_or_create(customer=customer, complete=False)
        items=order.orderitem_set.all()
        cartItems=order.get_cart_items
    else:
        items=[]
        order={'get_cart_total':0, 'get_cart_items':0}
        cartItems=order['get_cart_items']

    products=Product.objects.all().order_by('id')
    paginator=Paginator(products, 3)
    page=request.GET.get('page', 1)
    
    try:
        posts=paginator.page(page)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        posts=paginator.page(paginator.num_pages)

    context={'products':products, 'cartItems':cartItems, 'page:':page, 'posts':posts}
    return render(request, 'store/store.html', context)

@login_required(login_url='store:login')
def checkout(request):
    if request.user.is_authenticated:
        customer=request.user.customer
        order, createed=Order.objects.get_or_create(customer=customer, complete=False)
        items=order.orderitem_set.all()
        cartItems=order.get_cart_items
        shipping=order.shipping
    else:
        items=[]
        order={'get_cart_total':0, 'get_cart_items':0, 'shipping':False}
        cartItems=order['get_cart_items']
        shipping=False
    context={'items':items, 'order':order,'cartItems':cartItems, 'shipping':shipping, 'id':order.id}
    return render(request, 'store/checkout.html', context)

@login_required(login_url='store:login')
def cart(request):
    if request.user.is_authenticated:
        customer=request.user.customer
        order, createed=Order.objects.get_or_create(customer=customer, complete=False)
        items=order.orderitem_set.all()
        cartItems=order.get_cart_items
    else:
        items=[]
        order={'get_cart_total':0, 'get_cart_items':0}
        cartItems=order['get_cart_items']
    context={'items':items, 'order':order, 'cartItems':cartItems}
    return render(request, 'store/cart.html',context)


@login_required(login_url='store:login')
def updateItem(request):
    data=json.loads(request.body)
    productId=data['productId']
    action=data['action']
    print('Action:',action)
    print('ID:',productId)
    customer=request.user.customer
    product=Product.objects.get(id=productId)
    order, created=Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created=OrderItem.objects.get_or_create(order=order, product=product)
    if action=='add':
        orderItem.quantity=(orderItem.quantity+1)
    elif action=='remove':
        orderItem.quantity=(orderItem.quantity-1)

    orderItem.save()
    if orderItem.quantity<=0:
        orderItem.delete()
    return JsonResponse('Item added....',safe=False)

@login_required(login_url='store:login')
def processOrder(request):
    transaction_id=int(datetime.datetime.now().timestamp())
    data=json.loads(request.body)
    if request.user.is_authenticated:
        customer=request.user.customer
        order, created=Order.objects.get_or_create(customer=customer, complete=False)
        total=float(data['form']['total'])
        order.transaction_id=transaction_id
        if total==order.get_cart_total:
            order.complete=True
        order.save()

        if order.shipping==True:
            ShippingAddress.objects.create(
                customer=customer,
                order=order,
                address=data['shipping']['address'],
                city=data['shipping']['city'],
                state=data['shipping']['state'],
                zipcode=data['shipping']['zipcode'],
            )
            email="Order Confirmed for transaction id "+str(transaction_id)+"\nYour order will be delivered soon\n"
            email+="Shipping To: \n"+str(data['shipping']['address'])+"\n"+str(data['shipping']['city'])+"\n"+str(data['shipping']['state'])+"\n"
            email+="Total Amount: $"+str(total)+"\n                 "
            email+="Thank You Mr "+str(customer.name)+" for buying from us..\n"
            send_mail(
            'Order Confirmed',
            email,
            'sunderlaghari416@gmail.com',
            [customer.email],
            fail_silently=False,)

            print("Reached here")

    else:
        print("Not logged")
    return JsonResponse('Order processed...',safe=False)

@login_required(login_url='store:login')
def payment(request,pk):
    customer=request.user.customer
    cart=Order.objects.filter(id=pk, complete=False, customer=customer)
    if(len(cart)==0):
        return redirect('store:store')
    else:
        amount=cart[0].get_cart_total
        shipping=cart[0].shipping
        num=cart[0].get_cart_items
    
    context={'pk':pk, 'amount':amount, 'cartItems':num, 'shipping':shipping}
    return render(request, 'store/payment_form.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('store:store')
    else:
        if request.method=='POST':
            username=request.POST.get('username')
            password=request.POST.get('password')

            user=authenticate(request, username=username, password=password)

            if user is not None:
                auth_login(request, user)
                return redirect('store:store')
            else:
                messages.info(request, "Username or password is incorrect")
    return render(request, 'store/login.html')

def register(request):
     passFlag=0
     usernameFlag=0
     emailFlag=0
     phoneFlag=0
     nameFlag=0
     emailRegex='^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$'
     nameRegex='^[a-zA-Z ]+$'
     phoneRegex='\w{3}-\w{3}-\w{4}'
     usernameRegex='^[a-zA-Z0-9_.-]+$'
     if request.user.is_authenticated:
        return redirect('store:store')
     else:
        if request.method=='POST':
            username=request.POST.get('username')
            name=request.POST.get('name')
            email=request.POST.get('email')
            phone=request.POST.get('phone')
            password=request.POST.get('password')
            usernames=User.objects.filter(username=username)
            if(re.search(emailRegex,email)):
                emailFlag=1
            else:
                messages.info(request, "Invalid email")

            if(re.search(nameRegex,name)):
                nameFlag=1
            else:
                messages.info(request, "inavlid name")

            if(re.search(usernameRegex,username)):
                usernameFlag=1
                if(len(usernames)==1):
                    usernameFlag=0
                    messages.info(request, "Username Already exists")
            else:
                messages.info(request,'Invalid Username')
            
            if(re.search(phoneRegex,phone)):
                phoneFlag=1
            else:
                messages.info(request, 'Invalid Phone Number')
                messages.info(request, 'xxx-xxx-xxxx')




            if re.fullmatch(r'[A-Za-z0-9@#$%^&+=]{8,}', password):
                passFlag=1
            else:
                messages.info(request, "Password Should only contain\nuppercase letters: A-Z\nlowercase letters: a-z\nnumbers: 0-9\nany of the special characters: @#$%^&+=\n")
            
            if passFlag==1 and usernameFlag==1 and emailFlag==1 and phoneFlag==1 and nameFlag==1:
                user=User.objects.create(username=username, email=email)
                user.set_password(password)
                user.save()
                customer=Customer(user=user, name=name, phone=phone, email=email)
                customer.save()
                return redirect('store:login')
     return render(request, 'store/registration.html')
    


def logout(request):
    d_logout(request)
    return redirect('store:login')



def product(request, pk):
    customer=request.user.customer
    product=Product.objects.get(id=pk)
    rating_sum=0
    total_ratings=0
    ratings=Rating.objects.filter(product=product)
    for rating in ratings:
        rating_sum=rating_sum+rating.rated
        total_ratings=total_ratings+1
    comments=Comment.objects.filter(product=product).order_by('-id')
    order, created=Order.objects.get_or_create(customer=customer, complete=False)
    cartItems=order.get_cart_items
    if total_ratings!=0:
        avg_rating=rating_sum/total_ratings
    else:
        avg_rating=0
    if request.method=='POST':
        comment_sub=request.POST.get('comment')
        if(len(comment_sub)!=0):
            comment=Comment.objects.create(customer=customer, product=product, text= comment_sub)
            comment.save()
            return redirect('store:product',pk)
        else:
            return redirect('store:product',pk)


    context={'product':product, 'comments':comments, 'customer':customer, 'cartItems':cartItems, 'avg_rating':avg_rating, 'rated_by':total_ratings}
    return render(request, 'store/product.html', context)


def delete(request, pk, pk2):
    customer=request.user.customer
    comment=Comment.objects.filter(id=pk, customer=customer)
    if(len(comment)==0):
        return redirect('store:store')
    comment.delete()
    return redirect('store:product',pk2)


def rate(request, pk):
    product=Product.objects.filter(id=pk)
    customer=request.user.customer
    already_Rated=False
    ratings=Rating.objects.filter(customer=customer, product=product[0])
    if(len(ratings)!=0):

store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% load extras %}
{% block content %}
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">

				<a  class="btn btn-outline-dark" href="{% url 'store:store' %}">&#x2190; Continue Shopping</a>

				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
						<th><h5>Total:<strong> ${{order.get_cart_total}}</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'store:checkout' %}">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>${{item.product.price}}</p></div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-product="{{item.product.id}}" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}" data-action="add">
					
							<img data-product="{{item.product.id}}" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}" data-action="remove">
						</div>
					</div>
					<div style="flex:1"><p>${{item.get_total}}</p></div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock content %}

store/templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
     <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				
			</div>
				
			<br>
			<div class="box-element" id="payment-info">
				<small>Paypal Options</small>
				<a id='make-payment' href="{% url 'store:payment' id%}" class="btn btn-info">Make Payment</a>
			</div>
			
		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>${{item.product.price}}</p></div>
					<div style="flex:1"><p>x{{item.quantity}}</p></div>
				</div>
				{% endfor %}
				<h5>Items:   {{order.get_cart_items}}</h5>
				<h5>Total:   ${{order.get_cart_total}}</h5>
			</div>
		</div>
	</div>



	
{% endblock content %}

store/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Ecom</title>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

	<script type="text/javascript">
			var user='{{request.user}}'

			function getToken(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
		const csrftoken = getToken('csrftoken');
	</script>

	<style>
		body{
	background-color: hsl(0, 0%, 98%);
}

h1,h2,h3,h4,h5,h6{
	color:hsl(0, 0%, 30%);
}

.box-element{
	box-shadow:hsl(0, 0%, 80%) 0 0 16px;
	background-color: #fff;
	border-radius: 4px;
	padding: 10px;
}

.thumbnail{
	width: 100%;
	height: 200px;
	-webkit-box-shadow: -1px -3px 5px -2px rgba(214,214,214,1);
    -moz-box-shadow: -1px -3px 5px -2px rgba(214,214,214,1);
    box-shadow: -1px -3px 5px -2px rgba(214,214,214,1);
}

.product{
	border-radius: 0 0 4px 4px;
}

.bg-dark{
	background-color: #4f868c!important;
}

#cart-icon{
	width:25px;
	display: inline-block;
	margin-left: 15px;
}

#cart-total{
	display: block;
	text-align: center;
	color:#fff;
	background-color: red;
	width: 20px;
	height: 25px;
	border-radius: 50%;
	font-size: 14px;
}

.col-lg-4, .col-lg-6, .col-lg-8, .col-lg-12{
	margin-top: 10px;
}

.btn{
	border-radius: 0;
}

.row-image{
	width: 100px;
}

.form-field{
	width:250px;
	display: inline-block;
	padding: 5px;
}

.cart-row{
	display: flex;
    align-items: flex-stretch;
    padding-bottom: 10px;
    margin-bottom: 10px;
    border-bottom: 1px solid #ececec;

}

.quantity{
	display: inline-block;
	font-weight: 700;
	padding-right:10px;
	

}

.chg-quantity{
	width: 12px;
	cursor: pointer;
	display: block;
	margin-top: 5px;
	transition:.1s;
}

.chg-quantity:hover{
	opacity: .6;
}


.hidden{
	display: none!important;
}
	</style>

</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <a class="navbar-brand" href="{% url 'store:store' %}">Ecom</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
			<a class="nav-link" href="{% url 'store:store' %}">Store <span class="sr-only">(current)</span></a>
		  </li>

		  <li class="nav-item active">
			<a class="nav-link"><span class="sr-only">(current)</span></a>
		  </li>

		  <li class="nav-item active">
			<a class="nav-link"><span class="sr-only">(current)</span></a>
		  </li>

		  <li class="nav-item active">
			<a class="nav-link"><span class="sr-only">(current)</span></a>
		  </li>

		  <li class="nav-item active">
			<a class="nav-link"><span class="sr-only">(current)</span></a>
		  </li>

		  <li class="nav-item active">
			<a class="nav-link">Welcome {{request.user}} <span class="sr-only">(current)</span></a>
	      </li>
	 
	    </ul>
	    <div class="form-inline my-2 my-lg-0">
	     	<a href="{% url 'store:logout' %}"class="btn btn-warning">Logout</a>
	     	
	     	<a href="{% url 'store:cart' %}">
	    		<img  id="cart-icon" src="{% static 'images/cart.png' %}">
	    	</a>
	    	<p id="cart-total">{{cartItems}}</p>

	    </div>
	  </div>
	</nav>

     <div class="container">
            <br>
            {% block content %}


            {% endblock content %}
         </div>


	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
	
</body>
</html>

store/templates/store/pagination.html
<nav aria-label="Page navigation example" >
 
    <ul class="pagination">
 
        <li class="page-item">
 
            {% if page.has_previous %}
            <a class="page-link" href="?page={{page.previous_page_number}}">Previous</a>
 
            {% endif %}
 
        </li>
 
        <li class="page-item">
 
            <a class="page-link">Page {{page.number}} of {{page.paginator.num_pages}}</a>
 
        </li>
 
 
    <li class="page-item">
 
            {% if page.has_next %}
            <a class="page-link" href="?page={{page.next_page_number}}">Next</a>
 
            {% endif %}
 
        </li>
 
 
    </ul>
 
 
 
</nav>

store/templates/store/product.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}

<style>

.comment-wrapper .panel-body {
    max-height:650px;
    overflow:auto;
}

.comment-wrapper .media-list .media img {
    width:64px;
    height:64px;
    border:2px solid #e5e7e8;
}

.comment-wrapper .media-list .media {
    border-bottom:1px dashed #efefef;
    margin-bottom:25px;
}
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 300px;
  margin: auto;
  text-align: center;
  font-family: arial;
}

.price {
  color: grey;
  font-size: 22px;
}

.card button {
  border: none;
  outline: 0;
  padding: 12px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
}

.card button:hover {
  opacity: 0.7;
}

*{
    margin: 0;
    padding: 0;
}
.rate {
    float: left;
    height: 46px;
    padding: 0 10px;
}
.rate:not(:checked) > input {
    position:absolute;
    top:-9999px;
}
.rate:not(:checked) > label {
    float:right;
    width:1em;
    overflow:hidden;
    white-space:nowrap;
    cursor:pointer;
    font-size:30px;
    color:#ccc;
}
.rate:not(:checked) > label:before {
    content: '★ ';
}
.rate > input:checked ~ label {
    color: #ffc700;    
}
.rate:not(:checked) > label:hover,
.rate:not(:checked) > label:hover ~ label {
    color: #deb217;  
}
.rate > input:checked + label:hover,
.rate > input:checked + label:hover ~ label,
.rate > input:checked ~ label:hover,
.rate > input:checked ~ label:hover ~ label,
.rate > label:hover ~ input:checked ~ label {
    color: #c59b08;
}
</style>
<div class="card">
    <img src="{{product.imageURL}}" alt="{{product.name}}" style="width:100%">
    <h1>{{product.name}}</h1>
    <p class="price">${{product.price}}</p>
    <p>{{product.description}}</p>
    <p>Rated: {{avg_rating|floatformat:1}}</p>
    <p>Rated By {{rated_by}} Customers</p>
      <a href="{% url 'store:rate' product.id %}" class="btn btn-info">Rate</a>

      
    <p><button>Add to Cart</button></p>
  </div>


  <div class="container">
    <div class="row bootstrap snippets bootdeys">
        <div class="col-md-8 col-sm-12">
            <div class="comment-wrapper">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Comment panel
                    </div>
                    <form action="" method="POST">
                        {% csrf_token %}
                    <div class="panel-body">
                        
                        <textarea class="form-control" placeholder="write a comment..." name="comment" rows="3"></textarea>
                        
                        <br>
                        <button type="submit" class="btn btn-info pull-right">Post</button>
                        </form>
                        <div class="clearfix"></div>
                        <hr>
                        <ul class="media-list">
                            {% for comment in comments %}
                            <li class="media">
                                
                                <div class="media-body">
                                    <span class="text-muted pull-right">
                                        <small class="text-muted">{{comment.posted_at}}</small>
                                    </span>
                                    <strong class="text-success">@{{comment.customer.name}}</strong>
                                    <p>
                                       {{comment.text}}.
                                    </p>
                                    {% if comment.customer == customer %}
                                    <a href="{% url 'store:delete' comment.id product.id%}" class="">Delete Comment</a>
                                    {% endif %}
                                </div>
                            </li>
                            {% endfor %}
                            
                        </ul>
                    </div>
                </div>
            </div>
    
        </div>
    </div>
    </div>





{% endblock content %}

store/templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
	<div class="row">
        {% for product in posts %}
		<div class="col-lg-4">
			<img class="thumbnail" src="{{product.imageURL}}">
			<div class="box-element product">
				<h6><strong>{{product.name}}</strong></h6>
				<hr>

				<button data-product="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
				<a class="btn btn-outline-success" href="{% url 'store:product' product.id%}">View</a>
				<h4 style="display: inline-block; float: right"><strong>${{product.price}}</strong></h4>

			</div>
		</div>
        {% endfor %}
		
		
	</div>

	{% include 'store/pagination.html' with page=posts %}

{% endblock content %}